name: Publish Docker
on: 
  push: 
    branches:
      - develop
jobs:
  latest-and-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: DockerHub login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build Dockerfile and push to DockerHub
        run: |
          REPO_NAME="xavierniu/cloudreve"
          docker buildx build \
            --platform linux/amd64 \
            -t ${REPO_NAME}:unstable -t ${REPO_NAME}:unstable-${GITHUB_SHA} -t ${REPO_NAME}:unstable-amd64 -t ${REPO_NAME}:unstable-amd64-${GITHUB_SHA} \
            --push \
            . -f Dockerfile
  arm64v8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: DockerHub login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build Dockerfile and push to DockerHub
        run: |
          REPO_NAME="xavierniu/cloudreve"
          docker buildx build \
            --platform linux/arm64 \
            -t ${REPO_NAME}:arm64v8-unstable -t ${REPO_NAME}:arm64v8-unstable-${GITHUB_SHA} \
            --push \
            . -f Dockerfile.aarch64
  arm32v7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: DockerHub login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build Dockerfile and push to DockerHub
        run: |
          REPO_NAME="xavierniu/cloudreve"
          docker buildx build \
            --platform linux/arm/v7 \
            -t ${REPO_NAME}:arm32v7-unstable -t ${REPO_NAME}:arm32v7-unstable-${GITHUB_SHA} \
            --push \
            . -f Dockerfile.armhf