name: Building Docker Image of Cloudreve
on: 
  push: 
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    step:
      - steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Preparing Works
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/cloudreve
          SHORTREF=${GITHUB_SHA::8}
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${SHORTREF}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION}"
          fi
          # set output for tags and docker image
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.prep.outputs.tags }}
# jobs:
#   latest-and-amd64:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master
#       - name: DockerHub login
#         env: 
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: |
#           echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
#       - name: Set up docker buildx
#         id: buildx
#         uses: crazy-max/ghaction-docker-buildx@v1
#         with:
#           buildx-version: latest
#       - name: Get tag name
#         id: tagName
#         uses: little-core-labs/get-git-tag@v3.0.2
#       - name: Build Dockerfile and push to DockerHub
#         run: |
#           REPO_NAME="xavierniu/cloudreve"
#           docker buildx build \
#             --platform linux/amd64 \
#             -t ${REPO_NAME}:latest -t ${REPO_NAME}:amd64 $([[ -z "${GIT_TAG_NAME}" ]] && echo "" || echo "-t ${REPO_NAME}:${GIT_TAG_NAME} -t ${REPO_NAME}:${GIT_TAG_NAME}-amd64")  \
#             --push \
#             . -f Dockerfile
#   arm64v8:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master
#       - name: DockerHub login
#         env: 
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: |
#           echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
#       - name: Set up docker buildx
#         id: buildx
#         uses: crazy-max/ghaction-docker-buildx@v1
#         with:
#           buildx-version: latest
#       - name: Get tag name
#         id: tagName
#         uses: little-core-labs/get-git-tag@v3.0.2
#       - name: Build Dockerfile and push to DockerHub
#         run: |
#           REPO_NAME="xavierniu/cloudreve"
#           docker buildx build \
#             --platform linux/arm64 \
#             -t ${REPO_NAME}:arm64v8 $([[ -z "${GIT_TAG_NAME}" ]] && echo "" || echo "-t ${REPO_NAME}:${GIT_TAG_NAME}-arm64v8")  \
#             --push \
#             . -f Dockerfile.aarch64
#   arm32v7:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master
#       - name: DockerHub login
#         env: 
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: |
#           echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
#       - name: Set up docker buildx
#         id: buildx
#         uses: crazy-max/ghaction-docker-buildx@v1
#         with:
#           buildx-version: latest
#       - name: Get tag name
#         id: tagName
#         uses: little-core-labs/get-git-tag@v3.0.2
#       - name: Build Dockerfile and push to DockerHub
#         run: |
#           REPO_NAME="xavierniu/cloudreve"
#           docker buildx build \
#             --platform linux/arm/v7 \
#             -t ${REPO_NAME}:arm32v7 $([[ -z "${GIT_TAG_NAME}" ]] && echo "" || echo "-t ${REPO_NAME}:${GIT_TAG_NAME}-arm32v7")  \
#             --push \
#             . -f Dockerfile.armhf
#   sync-readme:
#     runs-on: ubuntu-latest
#     needs: [latest-and-amd64, arm64v8, arm32v7]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master
#       - name: Sync README.md
#         uses: peter-evans/dockerhub-description@v2.1.0
#         env:
#           DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#           DOCKERHUB_REPOSITORY: xavierniu/cloudreve
